Add button mapping for quit/back on all scenes
satisfactorymodding/ficsit-cli pull request #11
Opened 2023-01-16 00:03 UTC by samox73

fixes sub task in #10

2023-01-16 23:20 UTC, SoMuchForSubtlety requested changes

2023-01-16 23:20 UTC, SoMuchForSubtlety commented on tea/scenes/apply.go
> +		case keys.KeyEnter:
bubbletea provides constants for key codes[^1]. Simply switch on `msg.Type`.

[^1]: https://pkg.go.dev/github.com/charmbracelet/bubbletea#KeyType

2023-06-12 08:29 UTC, budak7273 commented
Fixes #16

2023-06-12 08:33 UTC, Vilsol submitted a review, later dismissed

2023-06-12 11:09 UTC, Vilsol commented
Please sync your PR to latest master @samox73

2023-06-18 16:59 UTC, Vilsol approved these changes

2023-06-18 16:59 UTC, merged

2023-06-18 17:10 UTC, budak7273 commented
Thanks for your contributions!